### ISSUE TITLE
Energy Bug / German

### ISSUE THREAD

**Issue by HerrJava** [HyCraftHD/UMOD#59]
## Die Kabel bringen das Spiel beim Plazieren zum Freezen.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreLibLoadingPlugin (corelib-0.5-alpha-mc1.8-universal.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 14.08.16 19:36
Description: Ticking block entity

java.lang.AbstractMethodError: net.hycrafthd.umod.tileentity.TileEntityChargeStation.getPos()Lnet/minecraft/util/BlockPos;
    at net.hycrafthd.umod.api.energy.EnergyAPI.<init>(EnergyAPI.java:29)
    at net.hycrafthd.umod.tileentity.TileEntityChargeStation.func_73660_a(TileEntityChargeStation.java:168)
    at net.minecraft.world.World.func_72939_s(World.java:1735)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.hycrafthd.umod.api.energy.EnergyAPI.<init>(EnergyAPI.java:29)
    at net.hycrafthd.umod.tileentity.TileEntityChargeStation.func_73660_a(TileEntityChargeStation.java:168)

-- Block entity being ticked --
Details:
    Name: tile.charge.entity // net.hycrafthd.umod.tileentity.TileEntityChargeStation
    Block type: ID #203 (tile.charge // net.hycrafthd.umod.block.BlockChargeStation)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-308,57,58), Chunk: (at 12,3,10 in -20,3; contains blocks -320,0,48 to -305,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #203 (tile.charge // net.hycrafthd.umod.block.BlockChargeStation)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1735)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['HerrJava'/199, l='MpServer', x=-307,45, y=58,17, z=58,37]]
    Chunk stats: MultiplayerChunkCache: 81, 81
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -334,00,64,00,0,00 - World: (-334,64,0), Chunk: (at 2,4,0 in -21,0; contains blocks -336,0,0 to -321,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 2939 game time, 2939 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 75 total; [EntitySkeleton['Skelett'/22532, l='MpServer', x=-230,50, y=24,00, z=82,50], EntityZombie['Zombie'/23556, l='MpServer', x=-383,50, y=14,00, z=55,50], EntitySkeleton['Skelett'/22533, l='MpServer', x=-231,50, y=24,00, z=83,50], EntitySkeleton['Skelett'/22534, l='MpServer', x=-229,50, y=24,00, z=84,50], EntityBat['Fledermaus'/23561, l='MpServer', x=-249,32, y=23,05, z=122,05], EntityBat['Fledermaus'/22545, l='MpServer', x=-277,48, y=19,40, z=18,69], EntityBat['Fledermaus'/22546, l='MpServer', x=-277,05, y=20,74, z=17,08], EntitySkeleton['Skelett'/22567, l='MpServer', x=-298,50, y=26,00, z=-4,50], EntitySkeleton['Skelett'/22568, l='MpServer', x=-301,50, y=26,00, z=1,50], EntityCreeper['Creeper'/22575, l='MpServer', x=-247,50, y=15,00, z=79,50], EntityCreeper['Creeper'/22577, l='MpServer', x=-245,50, y=15,00, z=66,50], EntityZombie['Zombie'/22582, l='MpServer', x=-354,50, y=22,00, z=-4,50], EntityZombie['Zombie'/1084, l='MpServer', x=-368,50, y=26,00, z=37,50], EntitySkeleton['Skelett'/22591, l='MpServer', x=-229,50, y=12,00, z=66,50], EntityCreeper['Creeper'/22597, l='MpServer', x=-352,50, y=22,00, z=-4,50], EntitySkeleton['Skelett'/22598, l='MpServer', x=-355,50, y=22,00, z=-4,50], EntitySkeleton['Skelett'/22599, l='MpServer', x=-361,50, y=22,00, z=-0,88], EntityItem['item.tile.torch'/77, l='MpServer', x=-367,91, y=26,00, z=40,88], EntityZombie['Zombie'/22614, l='MpServer', x=-324,50, y=18,00, z=-6,50], EntityZombie['Zombie'/22615, l='MpServer', x=-325,50, y=18,00, z=-8,50], EntityItem['item.tile.torch'/89, l='MpServer', x=-344,72, y=23,00, z=30,53], EntityMinecartChest['container.minecart'/90, l='MpServer', x=-353,50, y=23,06, z=13,50], EntityZombie['Zombie'/22618, l='MpServer', x=-320,50, y=18,00, z=-11,50], EntityItem['item.tile.torch'/91, l='MpServer', x=-344,84, y=18,00, z=70,44], EntityItem['item.tile.rail'/93, l='MpServer', x=-335,13, y=18,00, z=11,75], EntityItem['item.tile.rail'/95, l='MpServer', x=-336,84, y=18,00, z=22,22], EntityItem['item.tile.rail'/97, l='MpServer', x=-337,88, y=18,00, z=21,25], EntityItem['item.tile.torch'/98, l='MpServer', x=-337,38, y=17,00, z=35,88], EntityItem['item.tile.torch'/99, l='MpServer', x=-336,16, y=17,00, z=44,69], EntityBat['Fledermaus'/22627, l='MpServer', x=-322,68, y=19,04, z=2,69], EntityMinecartChest['container.minecart'/100, l='MpServer', x=-339,50, y=15,06, z=72,50], EntityBat['Fledermaus'/22628, l='MpServer', x=-324,25, y=19,10, z=-10,53], EntityBat['Fledermaus'/22629, l='MpServer', x=-301,94, y=21,49, z=17,25], EntityItem['item.tile.torch'/102, l='MpServer', x=-324,72, y=27,00, z=17,47], EntityBat['Fledermaus'/22630, l='MpServer', x=-301,48, y=18,95, z=11,92], EntityItem['item.tile.torch'/106, l='MpServer', x=-290,00, y=21,00, z=58,88], EntityBat['Fledermaus'/12397, l='MpServer', x=-323,25, y=21,10, z=-1,78], EntitySkeleton['Skelett'/22656, l='MpServer', x=-372,50, y=11,00, z=-3,50], EntityZombie['Zombie'/11393, l='MpServer', x=-301,81, y=26,00, z=6,69], EntitySpider['Spinne'/22658, l='MpServer', x=-251,00, y=26,22, z=72,06], EntityCreeper['Creeper'/11395, l='MpServer', x=-296,72, y=27,00, z=12,03], EntitySpider['Spinne'/22659, l='MpServer', x=-252,50, y=27,00, z=62,50], EntityItem['item.tile.rail'/1167, l='MpServer', x=-351,22, y=25,00, z=62,25], EntityZombie['Zombie'/22678, l='MpServer', x=-281,50, y=24,00, z=55,50], EntityCreeper['Creeper'/22706, l='MpServer', x=-328,50, y=27,00, z=56,50], EntityCreeper['Creeper'/22707, l='MpServer', x=-329,50, y=27,00, z=56,50], EntitySkeleton['Skelett'/6352, l='MpServer', x=-311,50, y=27,00, z=46,50], EntitySkeleton['Skelett'/6353, l='MpServer', x=-307,91, y=28,00, z=44,47], EntityZombie['Zombie'/23775, l='MpServer', x=-344,50, y=18,00, z=70,50], EntityZombie['Zombie'/23792, l='MpServer', x=-344,50, y=17,00, z=79,50], EntityCreeper['Creeper'/23794, l='MpServer', x=-346,41, y=17,00, z=74,97], EntityCreeper['Creeper'/23795, l='MpServer', x=-349,50, y=17,00, z=73,50], EntityZombie['Zombie'/284, l='MpServer', x=-360,50, y=22,00, z=-9,50], EntitySkeleton['Skelett'/13642, l='MpServer', x=-339,69, y=22,00, z=11,13], EntityCreeper['Creeper'/13643, l='MpServer', x=-343,50, y=22,00, z=10,50], EntityCreeper['Creeper'/13644, l='MpServer', x=-348,50, y=22,00, z=10,50], EntitySquid['Tintenfisch'/352, l='MpServer', x=-359,38, y=54,25, z=28,88], EntityCreeper['Creeper'/13699, l='MpServer', x=-330,50, y=46,00, z=23,50], EntitySkeleton['Skelett'/13700, l='MpServer', x=-327,50, y=10,00, z=77,50], EntitySquid['Tintenfisch'/520, l='MpServer', x=-336,09, y=58,31, z=98,47], EntityItem['item.tile.gravel'/1580, l='MpServer', x=-349,31, y=17,00, z=69,38], EntitySquid['Tintenfisch'/588, l='MpServer', x=-366,63, y=49,31, z=36,13], EntityZombie['Zombie'/4754, l='MpServer', x=-239,50, y=15,00, z=68,50], EntitySkeleton['Skelett'/4772, l='MpServer', x=-229,50, y=29,00, z=80,50], EntitySquid['Tintenfisch'/690, l='MpServer', x=-311,44, y=52,31, z=102,66], EntityPlayerSP['HerrJava'/199, l='MpServer', x=-307,45, y=58,17, z=58,37], EntityItem['item.tile.mushroom'/22333, l='MpServer', x=-344,69, y=52,00, z=10,81], EntityZombie['Zombie'/15169, l='MpServer', x=-326,22, y=27,00, z=3,13], EntityCreeper['Creeper'/15170, l='MpServer', x=-374,50, y=10,00, z=-8,50], EntityCreeper['Creeper'/15171, l='MpServer', x=-376,50, y=10,00, z=-8,50], EntityItem['item.item.dyePowder.black'/22415, l='MpServer', x=-308,66, y=54,00, z=35,22], EntityItem['item.item.dyePowder.black'/22416, l='MpServer', x=-307,63, y=52,00, z=35,13], EntityItem['item.item.rabbitHide'/22443, l='MpServer', x=-311,88, y=58,00, z=67,34], EntityItem['item.item.rabbitRaw'/22444, l='MpServer', x=-314,31, y=58,00, z=68,88], EntityBat['Fledermaus'/22447, l='MpServer', x=-300,46, y=19,02, z=15,18]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 934063336 bytes (890 MB) / 1326522368 bytes (1265 MB) up to 6335102976 bytes (6041 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1563.jar) 
    UCHIJAAAA   Forge{11.14.4.1563} [Minecraft Forge](forge-1.8-11.14.4.1563.jar) 
    UCHIJAAAA   corelib{0.5-alpha} [Core Libary](minecraft.jar) 
    UCHIJAAAA   umod{alpha0.1} [UMOD](umod-alpha0.1-1.8.0.jar) 
    Loaded coremods (and transformers): 
CoreLibLoadingPlugin (corelib-0.5-alpha-mc1.8-universal.jar)
  net.hycrafthd.corelib.asm.CoreLibASMTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.88' Renderer: 'GeForce GTX 960/PCIe/SSE2'
    Launched Version: 1.8-forge1.8-11.14.4.1563
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
```

**Comment by HerrJava** [comment]
Welt ist nach Freeze unladbar.

**Comment by HerrJava** [comment]
Alles was mit Strom zu tun hat (Auser Solarpanele) bringen das Spiel zum Crashen

**Comment by HyCraftHD** [comment]
Das Energiesystem ist im Moment broken ^^ @MrTroble sollte sich drumm kümmern.
